---
default_language_version:
    python: python3
fail_fast: false
minimum_pre_commit_version: 4.1.0
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: b89c5eef3ba3a74ecd506d968e63a8b80f697abf
      hooks:
          - id: check-json
          - id: check-yaml
            args: [--allow-multiple-documents]
            exclude: ^(\.github/)ISSUE_TEMPLATE/
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: detect-private-key
          - id: no-commit-to-branch
            args: [--branch, main]
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: cfc833bfc00c7cc40f702bd9e02df34d850d0291
      hooks:
          - id: markdownlint
            args: [--fix]
            stages: [manual]
    - repo: https://github.com/chrysa/pre-commit-tools
      rev: v0.1.1-54
      hooks:
          - id: yaml-sorter
            exclude: ^(\.github/)
          - id: json-sorter
          - id: env-file-check
