sonar.projectKey=chrysa_project-init
sonar.organization=chrysa
sonar.projectName=project-init
sonar.sources=project_init
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.mypy_cache/**
sonar.coverage.exclusions=tests/**
