---
name: Auto-update pre-commit hooks

on:
    schedule:
        - cron: '0 5 * * 1'
    workflow_dispatch:

jobs:
    call:
        uses: chrysa/github-actions/.github/workflows/auto-update-pre-commit.yml@main
