---
# Source : chrysa/shared-standards/templates/workflows-process/
# Nécessite .github/labeler.yml (mapping glob → label)
name: Pull Request Labels

on:
    pull_request:
    workflow_call:
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

run-name: 🏷️ apply labeler by ${{ github.actor }}

jobs:
    labels:
        name: Apply labels on pull request
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  persist-credentials: false
            - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6
              with:
                  sync-labels: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
