---
name: Release

on:
    push:
        branches: [main, master]
        paths-ignore:
            - '**.md'
            - .github/**
    workflow_dispatch:

jobs:
    call:
        uses: chrysa/github-actions/.github/workflows/release.yml@v1.2.0
        secrets:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}